in
out
err
test.py

